FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

RUN npm ci

ENV CHOKIDAR_USEPOLLING=1
ENV CI=false

EXPOSE 4200

CMD ["npx", "ng", "serve", "--host", "0.0.0.0", "--port", "4200", "--poll", "--disable-host-check"]
