services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bibliflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./bibliflow_backend
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  frontend:
    build: ./bibliflow_frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins
    user: "1000:1000"  # Ajustez selon votre UID:GID
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/workspace:rw  # Permissions lecture/écriture explicites
    environment:
      - JENKINS_OPTS=--tempDir=/var/jenkins_home/tmp
      - JAVA_OPTS=-Djava.awt.headless=true -Xmx1024m
    depends_on:
      - postgres
      - backend
      - frontend
      - sonarqube

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

volumes:
  postgres_data:
  jenkins_home:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs: