FROM jenkins/jenkins:lts

USER root

# Installer utilitaires, docker cli, docker-compose, node, npm, openjdk-17
RUN apt-get update && apt-get install -y \
    ca-certificates curl gnupg2 lsb-release wget unzip git \
    docker.io docker-compose nodejs npm openjdk-17-jdk-headless \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Ajouter jenkins au groupe docker
RUN usermod -aG docker jenkins

# Revenir à jenkins
USER jenkins
WORKDIR /var/jenkins_home
EXPOSE 8080 50000