FROM jenkins/jenkins:lts
USER root
RUN apt-get update && apt-get install -y docker.io docker-compose curl gnupg && curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && apt-get install -y nodejs && npm install -g sonar-scanner
USER jenkins
